from __future__ import annotations

from typing import Protocol


class FgDevice(Protocol):
    def open(self, resource: str) -> None: ...

    def apply(self, cfg: dict[str, float | str | bool]) -> None: ...

    def set_frequency_hz(self, freq_hz: float) -> None: ...

    def output(self, enabled: bool) -> None: ...

    def idn(self) -> str: ...

    def close(self) -> None: ...
